### PR TITLE
finer-grained bars

### PR DESCRIPTION
**Pull request by casperdcl**
- uses octet unicode bar chars
- ref: https://github.com/JohnPhamous/strava-box/pull/1 and https://github.com/jacc/music-box/pull/7

### CODE REVIEW

**Comment by casperdcl** [comment]
sure. I really like the idea of pinned gists. I noticed you're also starting to curate an awesome-list of them. Do you think it's worth creating an org for pinned gists and transferring everything there? cc: @jacc @JohnPhamous

**Comment by matchai** [comment]
I'd be open to the idea, though I haven't seen many being made in the last few months.

**Comment by johnletey** [comment]
@matchai I would be all for this move, and I wouldn't mind helping to maintain the org

One thing that this does bring up, is the fact that some of the repos use CircleCI, but you and Jason have moved to Github Actions. We should set some guidelines for pinned gist repos and make sure that all the repos follow them

**Comment by casperdcl** [comment]
yes I noticed this too. I think i'd prefer actions (though I haven't used them yet) since that means less reliance on external services and potentially tighter integration.

However as I noticed with strava-box, authentication tokens expire within 6 hours and connected "apps" need persistent storage to request new tokens. I implemented this by hacking around with the cache on circle-ci (https://github.com/JohnPhamous/strava-box/pull/1, https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13). Can github actions cache variables/files from cron jobs?

**Comment by casperdcl** [comment]
So @matchai, @JohnPhamous if you can confirm you're happy to move your repos to an open source org then we can discuss org names (`pinned-gist`?) Would ideally like a response from @jacc too though.

Happy to add everyone as maintainers unless anyone has any objections.

**Comment by matchai** [comment]
I don't think it's worth doing unless we see activity in the space of pinned gists. Right now it looks like things have stagnated, and this org would only serve to duplicate the consolidation done by the awesome list.

**Comment by jacc** [comment]
with @matchai here, i think we should keep it separate until the community picks up

**Pull request merged**
