### PR TITLE
Add more details on GitHub workflow activation

### LINKED ISSUE #19: Forked repo doesn't trigger action
Add this to readme https://github.community/t5/GitHub-Actions/Forked-repo-doesn-t-trigger-action/m-p/32575#M1189

### PR DESCRIPTION
**Pull request by fabiofdsantos**
Fixes #19.

GitHub actions are [disabled by default in forked repositories](https://github.community/t5/GitHub-Actions/How-to-run-and-enable-GitHub-actions-on-forked-repo-with-github/td-p/41619).

Also, I needed to implement [this workaround](https://github.community/t5/GitHub-Actions/Forked-repo-doesn-t-trigger-action/m-p/32575#M1189) to make it execute.

### CODE REVIEW

**Comment by HofmannZ** [comment]
LGTM

**Comment by fabiofdsantos** [comment]
@HofmannZ 
Are you referring to the pull request or the current's repository version?

**Comment by 1UC1F3R616** [comment]
How did u created a new workflow?

**Comment by fabiofdsantos** [comment]
@1UC1F3R616 Repository > Actions > New workflow > `set up a workflow yourself`

**Comment by miRoox** [comment]
To allow trigger on push might help this? like <https://github.com/miRoox/waka-box/pull/1>.

**Pull request closed without merging**
